import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className='grid min-h-screen place-items-center'>
				<h1 className='text-5xl font-bold'> Sacred Goddess Studio </h1>
			</main>
		</>
	);
}
